sudo: required
services:
  - docker

before_install:
  - docker build -t snghraj/docker-react -f Dockerfile.dev .

script:
  - docker run snghraj/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-731346202925"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: "$aws_secret_key"